
# This file is automatically generated, you probably don't want to edit this

ESnormOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ESnormOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            IV = NULL,
            DV = NULL, ...) {

            super$initialize(
                package="BrawStats",
                name="ESnorm",
                requiresData=TRUE,
                ...)

            private$..IV <- jmvcore::OptionVariable$new(
                "IV",
                IV)
            private$..DV <- jmvcore::OptionVariable$new(
                "DV",
                DV)

            self$.addOption(private$..IV)
            self$.addOption(private$..DV)
        }),
    active = list(
        IV = function() private$..IV$value,
        DV = function() private$..DV$value),
    private = list(
        ..IV = NA,
        ..DV = NA)
)

ESnormResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ESnormResults",
    inherit = jmvcore::Group,
    active = list(
        reportPlot = function() private$.items[["reportPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Effect Size")
            self$add(jmvcore::Image$new(
                options=options,
                name="reportPlot",
                title=" ",
                width=500,
                height=100,
                renderFun=".plotReport"))}))

ESnormBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ESnormBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "ESnorm",
                version = c(1,0,0),
                options = options,
                results = ESnormResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Effect Size
#'
#' 
#' @param data .
#' @param IV .
#' @param DV .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
ESnorm <- function(
    data,
    IV,
    DV) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ESnorm requires jmvcore to be installed (restart may be required)")

    if ( ! missing(IV)) IV <- jmvcore::resolveQuo(jmvcore::enquo(IV))
    if ( ! missing(DV)) DV <- jmvcore::resolveQuo(jmvcore::enquo(DV))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(IV), IV, NULL),
            `if`( ! missing(DV), DV, NULL))


    options <- ESnormOptions$new(
        IV = IV,
        DV = DV)

    analysis <- ESnormClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

