
# This file is automatically generated, you probably don't want to edit this

BrawStatsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawStatsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            IV = NULL,
            DV = NULL,
            show = "Infer", ...) {

            super$initialize(
                package="BrawStats",
                name="BrawStats",
                requiresData=TRUE,
                ...)

            private$..IV <- jmvcore::OptionVariable$new(
                "IV",
                IV)
            private$..DV <- jmvcore::OptionVariable$new(
                "DV",
                DV)
            private$..show <- jmvcore::OptionList$new(
                "show",
                show,
                options=list(
                    "Sample",
                    "Describe",
                    "Infer"),
                default="Infer")

            self$.addOption(private$..IV)
            self$.addOption(private$..DV)
            self$.addOption(private$..show)
        }),
    active = list(
        IV = function() private$..IV$value,
        DV = function() private$..DV$value,
        show = function() private$..show$value),
    private = list(
        ..IV = NA,
        ..DV = NA,
        ..show = NA)
)

BrawStatsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawStatsResults",
    inherit = jmvcore::Group,
    active = list(
        graphPlot = function() private$.items[["graphPlot"]],
        reportPlot = function() private$.items[["reportPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Full Analysis")
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=500,
                height=300,
                renderFun=".plotGraph"))
            self$add(jmvcore::Image$new(
                options=options,
                name="reportPlot",
                title=" ",
                width=500,
                height=200,
                renderFun=".plotReport"))}))

BrawStatsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawStatsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawStats",
                version = c(1,0,0),
                options = options,
                results = BrawStatsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Full Analysis
#'
#' 
#' @param data .
#' @param IV .
#' @param DV .
#' @param show .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
BrawStats <- function(
    data,
    IV,
    DV,
    show = "Infer") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawStats requires jmvcore to be installed (restart may be required)")

    if ( ! missing(IV)) IV <- jmvcore::resolveQuo(jmvcore::enquo(IV))
    if ( ! missing(DV)) DV <- jmvcore::resolveQuo(jmvcore::enquo(DV))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(IV), IV, NULL),
            `if`( ! missing(DV), DV, NULL))


    options <- BrawStatsOptions$new(
        IV = IV,
        DV = DV,
        show = show)

    analysis <- BrawStatsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

